# Tensors

Tensors are THE data structure in machine learning. A tensor is a structure very similar to a numpy array, but it can be used on GPUs. And GPUs we really need if we don't want to get old waiting ...

## Basics: initialization, shape, type and device

### Initialization

You can create tensors from numpy arrays and various other data types.

In [1]:
# create a dummy array
import numpy as np
example_array = np.array([1, 2, 3, 4, 5])
print("the array: ", example_array)

the array:  [1 2 3 4 5]


In [2]:
# convert the array to a tensor
import torch
example_tensor = torch.tensor(example_array)
print("the tensor: ", example_tensor)
# there are more functions of how to convert to a tensor
# but I like this general one because it is more flexible

the tensor:  tensor([1, 2, 3, 4, 5])


In [26]:
# other initialization options
# list
torch.tensor([1,2,3,4,5])
# tuple
torch.tensor((1,2,3,4,5))
# ranges
torch.tensor(range(1,6))
# floats and integers
torch.tensor(0.5)
# dataframes
import pandas as pd
df = pd.DataFrame({'a': [1,2,3,4,5], 'b': [6,7,8,9,10]})
torch.tensor(df.values)

tensor([[ 1,  6],
        [ 2,  7],
        [ 3,  8],
        [ 4,  9],
        [ 5, 10]])

In [12]:
# another very helpful one: create an array of zeros (great placeholder)

# create an array of 2 zeros
torch.zeros(2)

tensor([0., 0.])

More creation options can be found [in the docs](https://pytorch.org/docs/stable/torch.html#creation-ops)

### Shape, dtype and device

A tensor has 3 attributes:
- shape
- data type
- device

these words you will often see in error messages, because PyTorch complains about shapes not matching, and data types and devices not being the same.

In [4]:
example_array = np.array([1, 2, 3, 4, 5])
print("the array: ", example_array)
print("with shape: ", example_array.shape)
print("and dtype: ", example_array.dtype)

the array:  [1 2 3 4 5]
with shape:  (5,)
and dtype:  int64


In [9]:
example_tensor = torch.tensor(example_array)
print("its shape: ", example_tensor.shape)
print("its dtype: ", example_tensor.dtype)
print("its device: ", example_tensor.device)

its shape:  torch.Size([5])
its dtype:  torch.int64
its device:  cpu


In [16]:
# tensors can have as many dimensions as you wish
example_tensor = torch.zeros(2, 3)
print(example_tensor)
print("shape: ", example_tensor.shape)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
shape:  torch.Size([2, 3])


In [10]:
print("its size (in memory): ", example_tensor.element_size()) #returns size in bytes

# you can initialize a tensor with a specific dtype
example_tensor = torch.tensor(example_array, dtype=torch.int8)
print("new dtype: ", example_tensor.dtype)
print("new size (in memory): ", example_tensor.element_size())

its size (in memory):  8
new dtype:  torch.int8
new size (in memory):  1


In [18]:
# the device (where your tensor is stored) is CPU per default
# if you have a GPU, you can move your tensor there

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print("device available: ", device)
example_tensor = example_tensor.to(device)
print("device after moving: ", example_tensor.device)

device available:  cpu
device after moving:  cpu


## Tensor operations

### Indexing, slicing and concatenating

In [39]:
# create a tensor
tensor = torch.tensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

# select the first row
result1 = tensor[0]

# select the first two columns
result2 = tensor[:, :2]

# select elements with a Boolean mask
mask = tensor > 5
result3 = tensor[mask] # careful, this is not in the original structure anymore

print("first row: ", result1)
print("first 2 columns:\n", result2)
print("locations where tensor > 5:\n", mask)
print("elements that are > 5 (or elements of the mask locations)", result3)

first row:  tensor([1, 2, 3])
first 2 columns:
 tensor([[1, 2],
        [4, 5],
        [7, 8]])
locations where tensor > 5:
 tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])
elements that are > 5 (or elements of the mask locations) tensor([6, 7, 8, 9])


In [91]:
# create two tensors
tensor1 = torch.tensor([[1, 2],
                        [3, 4]])
tensor2 = torch.tensor([[5, 6],
                        [7, 8]])

# concatenate the two tensors along the second dimension
result1 = torch.cat((tensor1, tensor2), dim=1)

print(result1)

tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


More options can be found [in the docs](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

### Element-wise operations

In [29]:
# create two tensors
tensor1 = torch.tensor([[1, 1],
                        [2, 2]])
tensor2 = torch.tensor([[1, 2],
                        [3, 4]])

# add the two tensors element-wise
result = torch.add(tensor1, tensor2)

print(result)

tensor([[2, 3],
        [5, 6]])


These special element-wise operations give the same results as classic math operations (see below). However, using them instead of math operations can be more efficient. For small tensors, you don't have to worry about this though ;)

In [47]:
# add the two tensors element-wise
result = tensor1 + tensor2

print(result)

tensor([[2, 3],
        [5, 6]])


More options can be found [in the docs](https://pytorch.org/docs/stable/torch.html#pointwise-ops)

Some useful examples are
- sub
- mul
- div
- pow
- exp
- log

### Reduction operations

In [31]:
# create a tensor
tensor = torch.tensor([[1, 2],
                       [3, 4]])
print(tensor)

# sum the tensor along the first dimension
result = torch.sum(tensor, dim=0)

print(result)

tensor([[1, 2],
        [3, 4]])
tensor([4, 6])


More options can be found [in the docs](https://pytorch.org/docs/stable/torch.html#reduction-ops)

Some useful examples are
- mean
- min
- std
- count_nonzero


### Matrix operations

In [36]:
# create two matrices as tensors
matrix1 = torch.tensor([[1, 1],
                        [2, 2]])
matrix2 = torch.tensor([[1, 2],
                        [3, 4]])

# multiply the two matrices
result = torch.matmul(matrix1, matrix2)
# does [[m1(0,0)*m2(0,0) + m1(0,1)*m2(1,0)], [m1(1,0)*m2(0,0) + m1(1,1)*m2(1,0)]]

print(result)

tensor([[ 4,  6],
        [ 8, 12]])


More options can be found [in the docs](https://pytorch.org/docs/stable/torch.html#blas-and-lapack-operations)

## More advanced stuff

Here are some -in my opinion- importent behaviours of tensors I wish I had known earlier, but they are not necessary to get started in Pytorch. Let's see how it goes in the course up until here. Otherwise, feel free to have a look yourselves.

### Broadcasting

Broadcasting is a PyTorch feature that enables you to perform element-wise operations on tensors with different shapes. In my opinion, this is one of the most useful but hidden features of torch.
The rules about broadcasting are:
- If two tensors have the same number of dimensions, their shapes must either be equal or one of them must be 1 in all dimensions.
- If two tensors have different numbers of dimensions, the tensor with fewer dimensions is expanded by adding dimensions of size 1 on the left until the number of dimensions matches.

Here is a figure demonstrating the rules:

<img src="../images/tensor_broadcasting.png" width="300">

So let's have a look at the code.

In [60]:
# tensor with shape (2, 3)
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
# tensor with shape (3,)
tensor2 = torch.tensor([1, 2, 3])
result = tensor1 + tensor2
print(result)

tensor([[2, 4, 6],
        [5, 7, 9]])


In [61]:
# tensor with shape (2, 3)
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
# tensor with shape (2,)
tensor2 = torch.tensor([1, 2])
result = tensor1 + tensor2
print(result)

RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [62]:
# tensor with shape (2, 3)
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
# tensor with shape (2, 1)
tensor2 = torch.tensor([1, 2]).unsqueeze(1)
result = tensor1 + tensor2
print(result)

tensor([[2, 3, 4],
        [6, 7, 8]])


### Tensor modification

As briefly shown, we can change the dimensions and shapes of tensors as we please.

You can add and remove dimensions:
- tensor.<span style="color:slateblue">squeeze</span>() reduces a given dimension
- tensor.<span style="color:slateblue">unsqueeze</span>() adds a dimension in a given position

In [17]:
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])

print("original shape:\n   ", tensor1.shape)
print("unsqueezing the first dimension:\n   ", tensor1.unsqueeze(0).shape)
print("unsqueezing the second dimension:\n   ", tensor1.unsqueeze(1).shape)
print("unsqueezing the last dimension:\n   ", tensor1.unsqueeze(-1).shape)

original shape:
    torch.Size([2, 3])
unsqueezing the first dimension:
    torch.Size([1, 2, 3])
unsqueezing the second dimension:
    torch.Size([2, 1, 3])
unsqueezing the last dimension:
    torch.Size([2, 3, 1])


In [90]:
# what can we squeeze?

# if the dimension to be squeezed is larger than 1, nothing happens
print("shape of squeezed tensor:\n   ", tensor1.squeeze(0).shape)

tensor2 = torch.tensor([[1, 2, 3]])
print("new tensor of shape:\n   ", tensor2.shape)
print("shape of the squeezed new tensor:\n   ", tensor2.squeeze(0).shape)

shape of squeezed tensor:
    torch.Size([2, 3])
new tensor of shape:
    torch.Size([1, 3])
shape of the squeezed new tensor:
    torch.Size([3])


You can also change the shapes completely
- tensor.<span style="color:slateblue">view</span>()
- tensor.<span style="color:slateblue">expand</span>()

You can understand viewing and reshaping as taking the tensor's values in their natural occurance, that means our tensor

| | c1 | c2 | c3 |
| --- | :---: | :---: | :---: |
| r1 | 1 | 2 | 3 |
| r2 | 4 | 5 | 6 |

Is first going by row, then by column. The order of elements can be seen by flattening the tensor.

In [18]:
tensor1 = torch.tensor([[1, 2, 3],
                        [4, 5, 6]])
print(tensor1.flatten())

tensor([1, 2, 3, 4, 5, 6])


When using view, the tensor elements are sorted into the new defined shape.

In [19]:
print(tensor1.view(3,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


I can also let torch do some of the thinking for me. If I have a 2d tensor, I only have to specify the new size of one dimension, the other one will be defined `automatically`.

In [20]:
print(tensor1.view(-1,2))

tensor([[1, 2],
        [3, 4],
        [5, 6]])


So what are these reshaped tensors?

In [79]:
print("memory address of tensor1:\n",hex(tensor1.storage().data_ptr()))

tensor2 = tensor1.view(-1)

print("memory address of tensor2:\n",hex(tensor2.storage().data_ptr()))

memory address of tensor1:
 0x7f7b8b56cf40
memory address of tensor2:
 0x7f7b8b56cf40


See that tensor1 and tensor2 have the same memory address?
The view is not creating a new tensor, but just a different `view` on the same tensor. We call tensor2 a `pointer`. If you want this as a new and independent tensor, make a copy of unsing tensor.<span style="color:slateblue">clone</span>().

In [80]:
tensor2 = tensor1.clone().view(-1,2)
print("memory address of tensor2:\n",hex(tensor2.storage().data_ptr()))

memory address of tensor2:
 0x7f7b8b572a40


If you don't just need a new view, but for some reason you need to make the tensor bigger in some dimension, you can use tensor.<span style="color:slateblue">expand</span>().

In [26]:
tensor3 = torch.tensor([[1, 2, 3]])
print("original tensor size:\n", tensor3.shape)

# expanding the tensor in dimension 0 (first dimension), keeping the other dimension the same
tensor3.expand(2, -1)

original tensor size:
 torch.Size([1, 3])


tensor([[1, 2, 3],
        [1, 2, 3]])